version: '3.9'
services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 dj_dockerize.wsgi:application 
             mynginx1 -p 80:80 -d nginx
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on: -db - postgres
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: todoapp
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  web:
  postgres:
  db:
